vm-run: Configurable overlay file size

diff --git a/bin/vm-run b/bin/vm-run
--- a/bin/vm-run
+++ b/bin/vm-run
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 #
-# Version 0.0.1
-# 
+# Run libvirt qemu VM with optionally ephemeral overlay.
+#
+# Author: Davide Galassi <davxy@datawok.net>
+# Version: 0.0.2
+#
 # Guest XML config:
 # /etc/libvirt/qemu/<GUEST>.xml
 # Once the file is manually modified to apply the changes:
@@ -9,6 +12,7 @@
  
 NETWORK="default"
 GUEST="arch-vr"
+OVERLAY_MAX_SIZE=8G
 
 TMPFS_DIR="/mnt/ramdisk"
 OVERLAY="${TMPFS_DIR}/${GUEST}-overlay.qcow2"
@@ -28,13 +32,13 @@ help() {
 start_network() {
   if virsh net-list | grep -q "${NETWORK}.*active"; then
     echo "Network ${NETWORK} is already active."
-    return
+    return 0
   fi
 
   echo "Starting network ${NETWORK}..."
   if ! virsh net-start "${NETWORK}"; then
     echo "Failed to start network: ${NETWORK}" >&2
-    exit 1
+    return 1
   fi
 
   max_retries=10
@@ -42,13 +46,14 @@ start_network() {
   while ! virsh net-list | grep -q "${NETWORK}.*active"; do
     if [[ $retries -ge $max_retries ]]; then
       echo "Network ${NETWORK} did not shut down after $max_retries attempts."
-      exit 1
+      return 1
     fi
     echo "Waiting for network ${NETWORK} to start... Attempt $((retries + 1))/$max_retries"
     sleep 3
     ((retries++))
   done
   do_stop_network=1
+  return 0
 }
 
 stop_network() {
@@ -82,13 +87,13 @@ stop_network() {
 start_guest() {
   if virsh list | grep -q "${GUEST}.*running"; then
     echo "Guest ${GUEST} is already running."
-    return
+    return 0
   fi
 
   echo "Starting guest ${GUEST}..."
   if ! virsh start "${GUEST}"; then
     echo "Failed to start guest: ${GUEST}" >&2
-    exit 1
+    return 1
   fi
 
   max_retries=10
@@ -96,18 +101,19 @@ start_guest() {
   while ! virsh list | grep -q "${GUEST}.*running"; do
     if [[ $retries -ge $max_retries ]]; then
       echo "Guest ${GUEST} did not started after $max_retries attempts."
-      exit 1
+      return 1
     fi
     echo "Waiting for guest ${GUEST} to start... Attempt $((retries + 1))/$max_retries"
     sleep 3
     ((retries++))
   done
   do_stop_guest=1
+  return 0
 }
 
 stop_guest() {
   if [[ $do_stop_guest == 0 ]]; then
-    return 0
+    return
   fi
 
   if ! virsh list | grep -q "${GUEST}.*running"; then
@@ -144,16 +150,19 @@ prepare_overlay() {
   echo "Finding the base image for VM: ${GUEST}..."
   BASE_IMAGE=$(virsh domblklist "${GUEST}" --details | awk '$2 == "disk" {print $4}')
   if [[ -z "${BASE_IMAGE}" ]]; then
-    echo "Error: Unable to locate the base image for VM ${GUEST}." >&2
+    echo "Error: base image for VM ${GUEST} not defined." >&2
     exit 1
   fi
-  echo "Base image found: ${BASE_IMAGE}"
+  if [[ ! -f "${BASE_IMAGE}" ]]; then
+    echo "Error: base image for VM ${GUEST} not found." >&2
+    exit 1
+  fi
 
   # Create a tmpfs directory for the overlay
   echo "Setting up tmpfs directory..."
   if ! mountpoint -q "${TMPFS_DIR}"; then
     sudo mkdir -p "${TMPFS_DIR}"
-    sudo mount -t tmpfs -o size=4G tmpfs "${TMPFS_DIR}" 
+    sudo mount -t tmpfs -o size=${OVERLAY_MAX_SIZE} tmpfs "${TMPFS_DIR}" 
   fi
 
   # Create an overlay in RAM
@@ -173,19 +182,22 @@ prepare_overlay() {
   set +o pipefail
 }
 
+# Restore original VM configuration
+restore_original() {
+  echo "Restoring original VM configuration..."
+  echo "${vm_config}" | virsh define /dev/stdin
+  echo "VM configuration restored."
+}
+
+# Commit overlay
 commit_overlay() {
   echo "Committing overlay changes into the base image..."
   sudo qemu-img commit "${OVERLAY}"
   echo "Changes have been successfully merged into the base image."
 }
 
+# Clean up the tmpfs directory
 delete_overlay() {
-  # Restore original VM configuration
-  echo "Restoring original VM configuration..."
-  echo "${vm_config}" | virsh define /dev/stdin
-  echo "VM configuration restored."
-
-  # Clean up the tmpfs directory
   echo "Cleaning up..."
   if [[ $do_wipe == 1 ]]; then
     echo "Wiping"
@@ -198,16 +210,32 @@ delete_overlay() {
 }
 
 run() {
+  start_network
+  if [[ $? == 1 ]]; then
+    exit 1
+  fi
+
   if [[ $do_overlay == 1 ]]; then
     sudo -v
     prepare_overlay
   fi
-
-  start_network
   start_guest
-  virt-manager -c qemu:///system --show-domain-console arch-vr > /dev/null 2>&1 &
-  vm_manager_pid=$!
-  wait "${vm_manager_pid}"
+  start_res=$?
+  if [[ $do_overlay == 1 ]]; then
+    restore_original
+  fi
+  if [[ $start_res == 1 ]]; then
+    exit 1
+  fi
+
+  # virt-manager -c qemu:///system --show-domain-console ${GUEST} > /dev/null 2>&1 &
+  virt-viewer -a --domain-name ${GUEST} > /dev/null 2>&1 &
+  local viewer_pid=$!
+
+  echo "Waiting for virt-manager (${viewer_pid})"
+  wait "${viewer_pid}"
+  echo "virt-manager manager stopped"
+
   stop_guest
   stop_network
 
